#!/usr/bin/env bash
# Script to install Nginx server and redirect /redirect_me
apt-get -y update
apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.html
sed -i "s/server_name _;/server_name _;\n\trewrite ^\/redirect_me https://github.com/anthony-ndegwa-dev/Anthony-ndegwa-dev.github.io" /etc/nginx/sites-available/default
service nginx start
