#!/usr/bin/env bash
"""
Configure web-02 to be identical to web-01. Bash scripts from the web server
project will now come in handy to easily configure web-02.

We’re placing web servers behind a load balancer for this project, we want
to add a custom Nginx response header. The goal is to be able to track which
web server is answering our HTTP requests, to understand and track the way a
load balancer works.

Requirements:
    Configure Nginx to have custom header (on web-01 and web-02) HTTP response
        The name of custom HTTP header must be X-Served-By
        Value of custom HTTP header must be the hostname Nginx is running on
    Write 0-custom_http_response_header to configure a brand new Ubuntu machine
        to the requirements asked in this task
"""
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html
command="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;"
error="\n\terror_page 404 \/custom_404.html;\n\tlocation = \/custom_404.html {\n\troot \/usr\/share\/nginx\/html;\n\tinternal;}"
sed -i "s/server_name _;/$command$error/" /etc/nginx/sites-available/default
sed -i "s/include \/etc\/nginx\/sites-enabled\/\*;/include \/etc\/nginx\/sites-enabled\/\*;\n\tadd_header X-Served-By \"$HOSTNAME\";/" /etc/nginx/nginx.conf
service nginx start
