#!/usr/bin/env bash
# Script that configures HAproxy in a load balancer
sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.0
apt-get -y update
apt-get -y install haproxy=2.0.\*
echo -e "\nfrontend http\n\tbind *:80\n\tmode http\n\tdefault_backend web-backend\n\nbackend web-backend\n\tbalance roundrobin\n\tserver 106206-web-01 34.234.193.7:80 check\n\tserver 106206-web-02 54.174.67.136:80 check" >> /etc/haproxy/haproxy.cfg
service haproxy restart
