#!/usr/bin/env bash
# Script to fix what’s keeping Ubuntu container’s Nginx installation from listening on port 80
sudo sed -i "s/listen 80 default_server;/listen 8080 default_server;/" /etc/nginx/sites-enabled/default
sudo sed -i "s/listen \[::\]:80 default_server ipv6only=off;/listen \[::\]:8080 default_server;/" /etc/nginx/sites-enabled/default
sudo sed -i "s/ ipv6only=on//" /etc/nginx/sites-available/default
sudo service nginx restart
