#!/usr/bin/env bash
#Script displaying Best School 10 times and Hi for 9th iteration.
x=1
while [ $x -le 10 ]
do
    echo "Best School"
    if [ $x -eq 9 ]
    then
	echo "Hi"
    fi
    ((x++))
done
